# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD'] = 'rppz-mdku-bivw-kgry'.to_s

default_platform(:ios)

platform :ios do
  lane :beta do
    sync_code_signing(type: 'appstore')
    build_app(
      scheme: 'Twibu',
      workspace: 'Twibu.xcworkspace',
      include_bitcode: true
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
