name: Deploy to App Distribution

on:
  push:
    branches:
      - develop
      - feature/fastlane

jobs:
  build:
    runs-on: macOS-10.14
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Cache gem
        uses: actions/cache@preview
        with:
          path: .bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Setup
        env:
          PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }} # In case of using match
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # In case of using match
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }} # In case of using carthage
        run: |
          sudo xcode-select -s /Applications/Xcode_11.app
          gem install bundler:1.17.2
          bundle install --path .bundle
          bundle exec fastlane install_library
      - name: Cache carthage
        uses: actions/cache@preview
        with:
          path: ./Carthage/Build/iOS
          key: ${{ runner.os }}-carthage-${{ hashFiles('Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Cache cocoapod
        uses: actions/cache@preview
        with:
          path: ./Pods
          key: ${{ runner.os }}-cocoapod-${{ hashFiles('Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapod-
      - name: Run Unittest
        env:
          PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }} # In case of using match
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # In case of using match
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }} # In case of using carthage
        run: |
          bundle exec fastlane unittest
      - name: Deploy to Firebase App Distribution
        env:
          PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }} # In case of using match
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # In case of using match
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }} # In case of using carthage
        run: |
          npm install -g firebase-tools
          bundle exec fastlane app_distribution
