name: Submit to AppStoreConnect

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-10.14
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v1
      - name: Cache gem
        uses: actions/cache@preview
        with:
          path: .bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Cache carthage
        uses: actions/cache@preview
        with:
          path: ./Carthage/Build/iOS
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Cache cocoapod
        uses: actions/cache@preview
        with:
          path: ./Pods
          key: ${{ runner.os }}-cocoapod-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapod-
      - name: Build ipa and submit
        env:
          PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }} # In case of using match
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # In case of using match
        run: |
          sudo xcode-select -s /Applications/Xcode_11.app
          gem install bundler:1.17.2
          bundle install
          bundle exec fastlane submit_appstore
